---
# Create a simple VM

- name: Create a simple VM instance
  hosts: localhost
  connection: local
  gather_facts: no
  
  roles:
    - syncrou.manageiq-automate
  
  tasks:
  - name: Get a vmdb object
    manageiq_vmdb:
      href: "services/80"
    register: vmdb_object
          
  - name: Deploy new VM instance
    ec2:
      key_name: "{{ my_key_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
      group: "{{ group_name }}"
      region: "{{ region }}"
      instance_tags:
        app: "{{  app_name }}"
    register: ec2
      
  - name: Service Linking via an object
    manageiq_vmdb:
      vmdb: "{{ vmdb_object }}"
      action: add_provider_vms
      data:
        uid_ems:
          - "{{ ec2.instances[0].id }}"
        provider:
          id: 10000000000002


  - debug: msg="TESTPLAYBOOKOUTPUT {{ ec2.instances[0].id }}"
