- name: Create a simple VM instance
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Deploy new VM instance
      ec2:
        key_name: "{{ my_key_name }}"
        instance_type: t2.micro
        image: ami-ac442ac3
        wait: yes
        count: 1
        vpc_subnet_id: subnet-23af3748
        assign_public_ip: yes
        group: "{{ group_name }}"
        region: eu-central-1
        instance_tags:
          app: "{{  app_name }}"
