
---
- hosts: all
  connection: ssh
  remote_user: ec2-user
  become_method : sudo
  become: yes
  gather_facts : no

  tasks:
  - name: Install httpd package
    yum:
      name: httpd

  - name: Start httpd service
    service:
      name: httpd
      state: started

  - name: Configure firewall
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: Start firewalld service
    service:
      name: firewalld
      state: restarted
