---
# Create a simple VM

- name: Create a simple VM instance
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
  - manageiq_validate_certs: false
  - auto_commit: true
  
  roles:
  - syncrou.manageiq-automate

  tasks:
  - name: "Get an attribute Test Play"
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_attribute:
        object: "root"
        attribute: "public_ip"
    register: public_ip
    
  - debug: msg="DEBUG Test Play {{ public_ip }}"
  
  - name: Save public_ip in $evm.root
    manageiq_automate:
      workspace: "{{ workspace }}"
      set_attribute:
        object: root
        attribute: public_ip
        value:  "{{ public_ip }}"
